server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/oauth_demo?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    dbcp2:
      validation-query: SELECT 1
      test-on-borrow: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
  main:
    banner-mode: console
  data:
    rest:
      base-path: /api
